services:
  yonchan:
    build: 
      target: dev
    image: yonchan:development
    container_name: yonchan_development
    env_file:
      - './backend/.env'
    restart: unless-stopped
    volumes:
      - ./backend:/src
      - ./backend:/public